[project]
name = "causal-inference-in-python-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "catboost>=1.2.8",
    "cvxpy>=1.7.3",
    "cycler>=0.12.1",
    "dowhy>=0.12",
    "fklearn>=4.0.1",
    "graphviz>=0.21",
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.8",
    "islp>=0.4.0",
    "lightgbm>=4.6.0",
    "linearmodels>=6.1",
    "matplotlib>=3.10.6",
    "nbval>=0.11.0",
    "networkx==2.8.8",
    "pandas>=2.3.2",
    "pip>=25.2",
    "pytest>=9.0.0",
    "requests>=2.32.5",
    "rpy2>=3.6.4",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.5",
    "toolz<1.0",
    "ucimlrepo>=0.0.7",
]

[tool.uv.sources]
fklearn = { git = "https://github.com/nubank/fklearn.git" }
